# Generated by Django 4.2.14 on 2024-07-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
